### PR TITLE
Import StringIO from io module when running on Python3

### PR DESCRIPTION
**Pull request by amirma**
from randomAccessReader import RandomAccessReader
---------------------------------------------------------------------------
ModuleNotFoundError                       Traceback (most recent call last)
<ipython-input-1-f34837a7c413> in <module>()
----> 1 from randomAccessReader import RandomAccessReader

~/.local/share/virtualenvs/pipenv-UfFdSzCR/lib/python3.6/site-packages/randomAccessReader/__init__.py in <module>()
     11 
     12 import csv
---> 13 import StringIO
     14 
     15 # ==========

ModuleNotFoundError: No module named 'StringIO'

### CODE REVIEW

**Comment by jegesh** [comment]
Did you close this intentionally? Is it not actually relevant?

**Comment by amirma** [comment]
After I submitted the pull request, I noticed my change set was based on a stale version of master and the fix was already in master. So I closed it. Sorry for the noise :-)

**Comment by jegesh** [comment]
No problems

**Comment by jegesh** [comment]
After a second glance, I think you were looking at your own fork of the repo.  Those changes don't exist in the main repository.

**Pull request closed without merging**
